### ISSUE TITLE
AppPage: Improve dependency popup

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#738] opened 2023-01-11 11:25 UTC
I love the work @Feichtmeier did with [the update page](https://github.com/ubuntu-flutter-community/software/issues/480#issuecomment-1301819085). Could we do something to give this list a bit more context? Besides the filename, there's also a tagline and a description available for each package.

![image](https://user-images.githubusercontent.com/3986894/213870191-7041ca20-48fb-47a2-905f-e1ba2eb05459.png)

_Originally posted by @madsrh in https://github.com/ubuntu-flutter-community/software/issues/718#issuecomment-1376507422_

**Comment by madsrh** [comment] 2023-01-21 14:00
I've updated mockup since this is now in a dialog and not a section. The width of the BorderContainer should ofc align with the text 😉 #quickmockup

This is a duplicate of https://github.com/ubuntu-flutter-community/software/issues/739
Should we close one of them?

**Comment by Feichtmeier** [comment] 2023-01-21 14:07
yes move your mock up to the other issue and close this one please :+1:

**Closed** 2023-01-21 14:09 UTC
Labels: enhancement: UI :sparkles: :woman_artist:, difficulty: easy
