### ISSUE TITLE
Window control buttons are missing

### ISSUE THREAD

**Issue by soumyatheman** [ubuntu-flutter-community/software#330] opened 2022-09-30 18:32 UTC
Often I faced this issue, that the buttons to minimize, maximize and close isn't shown there. Sometimes things are even more wiered. Some screenshots below.
![Screenshot from 2022-09-30 23-57-07](https://user-images.githubusercontent.com/72045785/193334343-1b24533e-ad8d-47e7-876c-e5d6b74dc6e2.png)
![Screenshot from 2022-09-30 23-59-46](https://user-images.githubusercontent.com/72045785/193334361-287e15e3-8184-4a5f-84ed-407e4f374465.png)

Though they returns after some time, but I don't think that's ideal behavior.

**Comment by Feichtmeier** [comment] 2022-09-30 18:39
Yep! totally :) Will fix soon

Duplicate of #235

**Closed by Feichtmeier** 2022-09-30 18:39 UTC
