### ISSUE TITLE
Each application is given at least one review.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#1158] opened 2023-03-13 04:34 UTC
Even for applications where there shouldn't be any reviews, a review is added where most of its properties are null.

**Comment by madsrh** [comment] 2023-03-13 05:50
@whiskeyPeak this sounds like a duplicate of https://github.com/ubuntu-flutter-community/software/issues/1136

**Comment by whiskeyPeak** [comment] 2023-03-13 08:19
It's kinda the same issue albeit this one is more related to the service side of things. For some reason ```await file.readReviews();``` in ```odrs_service.dart```bnever yields null when there are no reviews.

**Comment by madsrh** [comment] 2023-03-13 08:27
You lost me there, but okay 😅  Feel to tackle both if you feel like it 😜

**Comment by Feichtmeier** [comment] 2023-03-23 08:12
Both the service and the UI are in this repo so this is the same issue. Let's please try to have the amount of issues to the exact amount that is needed to fix them (that doesn't mean to make unorganised task lists)

**Closed** 2023-03-23 08:12 UTC
Labels: prio: high
