### ISSUE TITLE
Controls in header bar disappear

### ISSUE THREAD

**Issue by fthx** [ubuntu-flutter-community/software#345] opened 2022-10-03 10:02 UTC
Hi,

After start-up:

![image](https://user-images.githubusercontent.com/23138504/193551266-5bf858f8-292c-407e-bfd1-5480d5c8a40f.png)

Then after few seconds, they are back.

**Comment by Feichtmeier** [comment] 2022-10-03 10:03
DUplicate of #235 :)

**Closed by Feichtmeier** 2022-10-03 10:03 UTC

**Comment by fthx** [comment] 2022-10-03 10:04
Okkkaaaayyyy, was not trivial to check this dup, hum?
^_^
