### ISSUE TITLE
Application shows a grey box when first opened, only resolved on relaunch or resize

### ISSUE THREAD

**Issue by local-optimum** [ubuntu-flutter-community/software#868] opened 2023-01-24 13:47 UTC
[Screencast from 24-01-23 13:43:01.webm](https://user-images.githubusercontent.com/55029393/214310791-05161bef-3833-4d75-ac43-212727f68158.webm)

Consistently, when I open the new application it displays a completely grey box, and only loads the inner assets when resizing the window or relaunching the app. This happens more than 50% of the time for me.

I have also had situations where the minimise, maximise, close buttons have disappeared though this is harder to reproduce.

**Comment by Feichtmeier** [comment] 2023-01-24 13:55
THat would be bad.I try to reproduce but this is not happening for me with the latest snap

https://user-images.githubusercontent.com/15329494/214312892-f2b971a8-6f6d-47f3-a64c-d228e08aa59e.mp4

@d-loose @madsrh could you try to reproduce this?

**Comment by jpnurmi** [comment] 2023-01-24 13:57
May be related to:
- https://github.com/flutter/engine/pull/38982

**Comment by Feichtmeier** [comment] 2023-01-24 14:03
I can't reproduce this on any of my computers though. COuld this be related to 22.10? @local-optimum what snap version and what ubuntu version to you use in this screencast?

**Comment by Feichtmeier** [comment] 2023-01-25 15:11
fresh lunar VM, I can not reproduce this issue

![image](https://user-images.githubusercontent.com/15329494/214599958-feaf69d3-c18b-4758-b5cb-64ce0730ef1c.png)

@local-optimum do you eventually use the noveau driver and an old nvidia card?

**Comment by d-loose** [comment] 2023-01-25 15:57
Couldn't reproduce it either so far

**Comment by local-optimum** [comment] 2023-01-25 17:21
I'm using an NVIDIA 1080 with the 525 proprietary driver. This isn't specific to this app, it happens to all Flutter apps on my machine...

**Comment by Feichtmeier** [comment] 2023-01-25 17:25
> I'm using an NVIDIA 1080 with the 525 proprietary driver. This isn't specific to this app, it happens to all Flutter apps on my machine...

Holy crap that's no good

All flutter snaps also from the store? Like the flutter gallery?

**Comment by local-optimum** [comment] 2023-01-25 17:28
Flutter gallery and QuickGUI I tried, both of them show the blank screen initially but eventually load the window contents (~1s), looks like only this app never displays. QuickGUI has in the past needed a resize but can't repro that atm.

**Comment by Feichtmeier** [comment] 2023-01-25 17:29
Okay 👍 thanks for investigating

Let's keep it opened here until we know what's happening

My tip is on the graphic card driver

**Comment by local-optimum** [comment] 2023-01-25 18:02
I tried the last three versions of NVIDIA and same issue (510, 515) but then switched to nouveau and the issue was gone and performance improved... very strange

**Comment by Feichtmeier** [comment] 2023-01-25 18:09
> I tried the last three versions of NVIDIA and same issue (510, 515) but then switched to nouveau and the issue was gone and performance improved... very strange

😳 That's not good. You won't be the only user with an Nvidia card

Maybe it's this issue?

https://github.com/flutter/flutter/issues/76178

**Comment by d-loose** [comment] 2023-01-26 15:01
> Couldn't reproduce it either so far

No issues with the snap (`preview/candidate: 0.2.7-alpha 2023-01-24 (847)`), but happens now somewhat consistently when running the release version built with `flutter build linux`. No NVIDIA card here though.

**Comment by jpnurmi** [comment] 2023-01-26 15:25
@d-loose Flutter 3.3.10 or 3.7.0?

**Comment by d-loose** [comment] 2023-01-26 15:37
Happens with both versions (checked it again now, with a clean repository)

**Comment by jpnurmi** [comment] 2023-01-26 15:45
Awesome, I'll try building a release version of the engine...

**Comment by Feichtmeier** [comment] 2023-01-26 15:51
Snap is still fine though for me here on both ubuntu laptops
I have the feeling that this is unrelated to this app here. @d-loose what card to you have then? and what driver?

**Comment by d-loose** [comment] 2023-01-26 15:53
AMD Renoir with the amdgpu driver

**Comment by Feichtmeier** [comment] 2023-01-26 15:56
Aha! :point_up: 
Maybe some dedicated graphic card stuff
Try the open source driver if you have time and nerves (noveau or seomthing... nivea?)

**Comment by local-optimum** [comment] 2023-01-26 15:58
Yeah i don't get the issue on nouveau (in fact I get better desktop performance in general on nouveau atm on my machine)

**Comment by Feichtmeier** [comment] 2023-01-26 16:40
@d-loose before you entered, local optimus mentioned that he only has this problem when he clicks on the app icon. Could this be anyhow related to graphic drivers AND your recent works on the unity-dash api badges?

**Comment by d-loose** [comment] 2023-01-26 16:46
I think that's very unlikely - all of the icon launcher magic is handled elsewhere, we're just sending signals over DBus and aren't affecting the UI in any way.

For me it happens randomly even when running it from the console:

https://user-images.githubusercontent.com/113362648/214896266-2acbccbf-7fc5-4aea-988c-f905844c066c.mp4

**Comment by Feichtmeier** [comment] 2023-01-26 16:49
can we control on which graphic card flutter processes are being rendered? I guess when you switch either the driver or the card this issue will go away
which would mean this needs to be fixed inside flutter @.@ :see_no_evil:

**Comment by whiskeyPeak** [comment] 2023-01-26 17:31
In my case, I can only reproduce the grey box on release builds.
The mouse is also responding to all of the different widget input methods (you can see it change throughout the video)

https://user-images.githubusercontent.com/73116038/214907005-4a79722f-4071-4051-ace8-40ba62ba169d.mp4

**Comment by jpnurmi** [comment] 2023-01-26 17:40
I'm able to reproduce the issue with the latest flutter main branch and a self-built engine that has optimizations turned on. I wasn't able to reproduce it with an earlier unoptimized build so I went to look at the flags they use for the official build shipped with flutter.

The underlying issue is that the `FlGLArea` child of `FlView` doesn't get a sensible size allocated but stays at 1x1. Here's a workaround that works for me:
```diff
diff --git a/linux/my_application.cc b/linux/my_application.cc
index e04849d..43422f4 100644
--- a/linux/my_application.cc
+++ b/linux/my_application.cc
@@ -75,6 +75,7 @@ static void my_application_activate(GApplication* application) {
   gtk_container_add(GTK_CONTAINER(window), GTK_WIDGET(view));
 
   fl_register_plugins(FL_PLUGIN_REGISTRY(view));
+  gtk_widget_realize(GTK_WIDGET(window));
   gtk_widget_show(GTK_WIDGET(window));
   gtk_widget_show(GTK_WIDGET(view));
   gtk_widget_grab_focus(GTK_WIDGET(view));
```

**Comment by Feichtmeier** [comment] 2023-01-26 17:42
awesome @jpnurmi thank you very much! I'll test your fix when the other PR is in

**Comment by whiskeyPeak** [comment] 2023-01-26 18:15
Uhm @Feichtmeier, testing this on 3.7 with your pr, they grey box is now gone.

**Comment by whiskeyPeak** [comment] 2023-01-26 18:26
O_o

https://user-images.githubusercontent.com/73116038/214918763-43302375-dfb0-4fa0-abb9-b7fcd37bd531.mp4

**Comment by jpnurmi** [comment] 2023-01-26 18:43
I think it's a race between the Flutter renderer vs. GTK. :racehorse:

**Comment by d-loose** [comment] 2023-01-26 19:06
> Here's a workaround that works for me:
> ...

Works!

**Comment by jpnurmi** [comment] 2023-01-27 08:07
I was going to push the workaround but after testing more I must admit it doesn't work reliably either... :(

When the Flutter renderer wins the race and the first frame arrives early enough so that FlView still has a size allocation queued, which in turn allocates a proper size for FlGlArea that makes it draw correctly:
```
Launching lib/main.dart on Linux in release mode...
Building Linux application...                                           

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
flutter engine: fl_view_realize 1x1
flutter engine: fl_renderer_start
flutter engine: fl_view_size_allocate 700x653
flutter engine: fl_view_size_allocate 860x813
flutter engine: fl_view_size_allocate 860x860
flutter engine: fl_gl_area_queue_render 1x1
flutter engine: fl_gl_area_realize 1x1
flutter engine: fl_view_size_allocate 860x860
flutter engine: fl_gl_area_size_allocate 860x860
flutter engine: fl_gl_area_queue_render 860x860
flutter engine: fl_gl_area_draw 860x860
flutter engine: fl_gl_area_queue_render 860x860
flutter engine: fl_gl_area_draw 860x860
```

When the Flutter renderer loses the race and the first frame arrives too late when FlView already has its final size allocated, FlGlArea never gets a size allocated so it draws nothing:
```
Launching lib/main.dart on Linux in release mode...
Building Linux application...                                           

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
flutter engine: fl_view_realize 1x1
flutter engine: fl_renderer_start
flutter engine: fl_view_size_allocate 700x653
flutter engine: fl_view_size_allocate 860x813
flutter engine: fl_view_size_allocate 860x860
flutter engine: fl_gl_area_queue_render 1x1
flutter engine: fl_gl_area_realize 1x1
flutter engine: fl_gl_area_queue_render 1x1
flutter engine: fl_gl_area_queue_render 1x1
flutter engine: fl_gl_area_queue_render 1x1
flutter engine: fl_gl_area_queue_render 1x1
[...]
```

**Comment by Feichtmeier** [comment] 2023-01-27 08:16
But was it always like this for dedicated GPUs? Or is this new with flutter version xyz?  As I never experienced and still do not experience this on intel CPUs with integrated graphic units

**Comment by jpnurmi** [comment] 2023-01-27 08:36
You may have better luck with different drivers but I don't think this is directly related to any specific GPUs. I don't know GTK well enough to say if we're missing something there. For example, is a custom GtkContainer that creates a child on the fly responsible for manually forcing size-allocation on the child or should GTK take care of that?

Anyway, I don't know why this issue is suddenly popping up but what makes this tricky is the non-deterministic behavior. Unrelated changes or even an innocent printf could change the sequence sufficiently to make the issue not surface because GTK's size allocation is connected to the frame clock.

**Comment by Feichtmeier** [comment] 2023-01-27 08:40
Ok 🤔 
Maybe this is one of the first flutter linux apps bringing the whole thing to the limits? There is quite a lot computation happening of the start of the app because of Appstream. Could this be related? Could you experience the same in the installer?

**Comment by jpnurmi** [comment] 2023-01-27 08:52
Could be, putting pressure on the system is one way to change the timings. I was also occasionally able to trigger the issue by running `stress` in the background. The release-mode tip from Dennis was a game changer - now it's a lot easier to reproduce. :) Oliver has seen this with other Flutter apps too. I think it was Quickemu, so it's not only those using handy_window.

**Closed** 2023-02-16 08:53 UTC
Labels: bug 🐛, external-issue, difficulty: hard, prio: high
