### ISSUE TITLE
Software centre takes a while to quit.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#880] opened 2023-01-26 17:24 UTC
Tested in release mode.

https://user-images.githubusercontent.com/73116038/214905461-b8f2fb02-41f8-4394-a699-7ee8ef4b68a6.mp4

**Comment by Feichtmeier** [comment] 2023-01-26 17:25
Duplicate of #868

**Comment by whiskeyPeak** [comment] 2023-01-26 17:28
Ah, this issue shows #868 in action but isn't what I'm referring to here. There is a significant delay when pressing the close button. The other issue only relates to the grey box. :)

**Comment by Feichtmeier** [comment] 2023-01-26 17:28
woops sorry

**Comment by Feichtmeier** [comment] 2023-01-26 17:33
Can not confirm with the PR opened at least, can't switch back now :)


https://user-images.githubusercontent.com/15329494/214907649-f97a6fad-7f64-483b-9f65-65d0267f80af.mp4

**Comment by whiskeyPeak** [comment] 2023-01-26 17:47
Yup can confirm, updating to 3.7 and with #879 the delay is gone :D

**Comment by Feichtmeier** [comment] 2023-01-26 17:50
Cool! Yeah yesterday was a big release update :) We managed to update our yaru libs in time (-1 day :P )

**Closed** 2023-01-26 18:47 UTC
Labels: bug 🐛, external-issue
