### ISSUE TITLE
can't go back to ExplorePage from search results

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#622] opened 2022-12-06 16:59 UTC
When on a search results page, we cannot go back to the ExplorePage by clicking on the icon.
(apologies for the terrible quality video :D)

https://user-images.githubusercontent.com/36884067/205974847-0ccd9e28-9329-4014-be02-2abae771d86f.mov

**Comment by Feichtmeier** [comment] 2022-12-06 17:19
Duplicate of #254 :D

**Closed by Feichtmeier** 2022-12-06 17:19 UTC
